import onemath     = liboneMath%lib{onemath}
import blas_mklcpu = liboneMath%lib{onemath_blas_mklcpu}
import libs        = gtest%liba{gtest} $onemath

import! clang_offload_packager = icpx%exe{clang-offload-packager}

blas_rt_src = cxx{main_test}    \
              rt/blas/cxx{**}

blas_ct_src = cxx{main_test}    \
              ct/cxx{**}

ld_library_path = "$($onemath: out_root)/src/:$getenv(LD_LIBRARY_PATH)"

./: exe{test_main_blas_rt}: testscript
./: exe{test_main_blas_ct}: testscript

for t: $blas_rt_src
{
  n = $name($t)
  d = $directory($t)

  exe{test_main_blas_rt}: $d/obje{$(n)_host.exe.o}: $libs
}

for t: $blas_ct_src
{
  n = $name($t)
  d = $directory($t)

  exe{test_main_blas_ct}: $d/obje{$(n)_host.exe.o}: $libs $blas_mklcpu
}

obje{*}: cxx.poptions += "-I$src_base/include"

rt/obje{*}: cxx.poptions += "-I$src_base/blas/include"  \
                            -DCALL_RT_API

ct/obje{*}: cxx.poptions += "-I$src_base/blas/include"

# Set up the reference BLAS implementation.
#
ref_blas_incdir = $config.liboneMath_tests.reference_blas_incdir
ref_blas_libdir = $config.liboneMath_tests.reference_blas_libdir

obje{*}: cxx.poptions +=                                        \
  "-I$ref_blas_incdir"                                          \
  -DONEMATH_REF_BLAS_LIBNAME="\"$ref_blas_libdir/libblas.so\""  \
  -DONEMATH_REF_CBLAS_LIBNAME="\"$ref_blas_libdir/libcblas.so\""

sycl_exe_src = $blas_rt_src $blas_ct_src
import [once] liboneMath%buildfile{sycl_compilation}

exe{test_main_blas_rt}: $libs
exe{test_main_blas_ct}: $libs $blas_mklcpu
