import! clang_offload_packager = icpx%exe{clang-offload-packager}

using autoconf

# Public headers.
#
pub = [dir_path] ../include/oneapi/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

# @@ TODO mklgpu, rocblas, ...
#
supported_backends = mklcpu

# Fail if no supported backends are enabled.
#
backends = [null]

if ($build.mode != 'skeleton')
{
  for b: $supported_backends
  {
    if $(config.liboneMath.enable_$(b)_backend)
      backends += $b
  }

  ifn $backends
    fail "no supported backends enabled"
  else
    text "enabled backends:" $backends
}

all_backend_libs = onemath_blas_mklcpu          \
                   onemath_lapack_mklcpu        \
                   onemath_dft_mklcpu           \
                   onemath_rng_mklcpu           \
                   onemath_sparse_blas_mklcpu

all_libs = onemath $all_backend_libs

# @@ TODO Having all libraries in one buildfile will probably become a problem
#    as more backends are added.

# The runtime dispatch library. It dlopen's the backend libraries as
# appropriate. Useful because otherwise client code needs to be linked against
# specific backend libraries (e.g. libonemath_blas_mklgpu).
#
./: lib{onemath}: include = true

# The Intel oneMKL CPU backend libraries (for compile-time dispatch).
#
./: lib{onemath_blas_mklcpu}:   include = $config.liboneMath.enable_mklcpu_backend
./: lib{onemath_lapack_mklcpu}: include = $config.liboneMath.enable_mklcpu_backend
./: lib{onemath_dft_mklcpu}:    include = $config.liboneMath.enable_mklcpu_backend
./: lib{onemath_rng_mklcpu}:    include = $config.liboneMath.enable_mklcpu_backend
./: lib{onemath_sparse_blas_mklcpu}: include = $config.liboneMath.enable_mklcpu_backend

# Public headers.
#
lib{$all_libs}: $pub/{$pub_hdrs} oneapi/math/detail/hxx{config}

# Metadata.
#
lib{onemath}:
{
  export.metadata = 1 libonemath

  libonemath.enable_armpl_backend = $config.liboneMath.enable_armpl_backend
  libonemath.enable_armpl_openrng = $config.liboneMath.enable_armpl_openrng
  libonemath.enable_cublas_backend = $config.liboneMath.enable_cublas_backend
  libonemath.enable_cufft_backend = $config.liboneMath.enable_cufft_backend
  libonemath.enable_curand_backend = $config.liboneMath.enable_curand_backend
  libonemath.enable_cusolver_backend = $config.liboneMath.enable_cusolver_backend
  libonemath.enable_cusparse_backend = $config.liboneMath.enable_cusparse_backend
  libonemath.enable_mklcpu_backend = $config.liboneMath.enable_mklcpu_backend
  libonemath.enable_mklgpu_backend = $config.liboneMath.enable_mklgpu_backend
  libonemath.enable_netlib_backend = $config.liboneMath.enable_netlib_backend
  libonemath.enable_generic_blas_backend = $config.liboneMath.enable_generic_blas_backend
  libonemath.enable_generic_blas_backend_amd_gpu = $config.liboneMath.enable_generic_blas_backend_amd_gpu
  libonemath.enable_generic_blas_backend_intel_cpu = $config.liboneMath.enable_generic_blas_backend_intel_cpu
  libonemath.enable_generic_blas_backend_intel_gpu = $config.liboneMath.enable_generic_blas_backend_intel_gpu
  libonemath.enable_generic_blas_backend_nvidia_gpu = $config.liboneMath.enable_generic_blas_backend_nvidia_gpu
  libonemath.generic_blas_enable_complex = $config.liboneMath.generic_blas_enable_complex
  libonemath.generic_blas_enable_usm = $config.liboneMath.generic_blas_enable_usm
  libonemath.enable_portfft_backend = $config.liboneMath.enable_portfft_backend
  libonemath.enable_rocblas_backend = $config.liboneMath.enable_rocblas_backend
  libonemath.enable_rocfft_backend = $config.liboneMath.enable_rocfft_backend
  libonemath.enable_rocrand_backend = $config.liboneMath.enable_rocrand_backend
  libonemath.enable_rocsolver_backend = $config.liboneMath.enable_rocsolver_backend
  libonemath.enable_rocsparse_backend = $config.liboneMath.enable_rocsparse_backend

  # True if the BLAS domain is enabled.
  #
  libonemath.enable_blas = ($config.liboneMath.enable_mklcpu_backend || \
                            $config.liboneMath.enable_mklgpu_backend)

  # True if the LAPACK domain is enabled.
  #
  libonemath.enable_lapack = ($config.liboneMath.enable_mklcpu_backend || \
                              $config.liboneMath.enable_mklgpu_backend)

  # True if the DFT domain is enabled.
  #
  libonemath.enable_dft = ($config.liboneMath.enable_mklcpu_backend || \
                           $config.liboneMath.enable_mklgpu_backend)

  # True if the RNG domain is enabled.
  #
  libonemath.enable_rng = ($config.liboneMath.enable_mklcpu_backend || \
                           $config.liboneMath.enable_mklgpu_backend)

  # True if the sparse BLAS domain is enabled.
  #
  libonemath.enable_sparse = ($config.liboneMath.enable_mklcpu_backend || \
                              $config.liboneMath.enable_mklgpu_backend)
}

# Generate config.hpp.
#
oneapi/math/detail/hxx{config}: in{config}
{
  autoconf.flavor = cmake

  ONEMATH_ENABLE_ARMPL_BACKEND = $config.liboneMath.enable_armpl_backend
  ONEMATH_ENABLE_ARMPL_OPENRNG = $config.liboneMath.enable_armpl_openrng
  ONEMATH_ENABLE_CUBLAS_BACKEND = $config.liboneMath.enable_cublas_backend
  ONEMATH_ENABLE_CUFFT_BACKEND = $config.liboneMath.enable_cufft_backend
  ONEMATH_ENABLE_CURAND_BACKEND = $config.liboneMath.enable_curand_backend
  ONEMATH_ENABLE_CUSOLVER_BACKEND = $config.liboneMath.enable_cusolver_backend
  ONEMATH_ENABLE_CUSPARSE_BACKEND = $config.liboneMath.enable_cusparse_backend
  ONEMATH_ENABLE_MKLCPU_BACKEND = $config.liboneMath.enable_mklcpu_backend
  ONEMATH_ENABLE_MKLGPU_BACKEND = $config.liboneMath.enable_mklgpu_backend
  ONEMATH_ENABLE_NETLIB_BACKEND = $config.liboneMath.enable_netlib_backend
  ONEMATH_ENABLE_GENERIC_BLAS_BACKEND = $config.liboneMath.enable_generic_blas_backend
  ONEMATH_ENABLE_GENERIC_BLAS_BACKEND_AMD_GPU = $config.liboneMath.enable_generic_blas_backend_amd_gpu
  ONEMATH_ENABLE_GENERIC_BLAS_BACKEND_INTEL_CPU = $config.liboneMath.enable_generic_blas_backend_intel_cpu
  ONEMATH_ENABLE_GENERIC_BLAS_BACKEND_INTEL_GPU = $config.liboneMath.enable_generic_blas_backend_intel_gpu
  ONEMATH_ENABLE_GENERIC_BLAS_BACKEND_NVIDIA_GPU = $config.liboneMath.enable_generic_blas_backend_nvidia_gpu
  ONEMATH_GENERIC_BLAS_ENABLE_COMPLEX = $config.liboneMath.generic_blas_enable_complex
  ONEMATH_GENERIC_BLAS_ENABLE_USM = $config.liboneMath.generic_blas_enable_usm
  ONEMATH_ENABLE_PORTFFT_BACKEND = $config.liboneMath.enable_portfft_backend
  ONEMATH_ENABLE_ROCBLAS_BACKEND = $config.liboneMath.enable_rocblas_backend
  ONEMATH_ENABLE_ROCFFT_BACKEND = $config.liboneMath.enable_rocfft_backend
  ONEMATH_ENABLE_ROCRAND_BACKEND = $config.liboneMath.enable_rocrand_backend
  ONEMATH_ENABLE_ROCSOLVER_BACKEND = $config.liboneMath.enable_rocsolver_backend
  ONEMATH_ENABLE_ROCSPARSE_BACKEND = $config.liboneMath.enable_rocsparse_backend

  # @@ TODO This controls only dllimport/export so not sure why it's defined
  #    in a header.
  #
  ONEMATH_BUILD_SHARED_LIBS = true
}

# Private headers and included source files.
#
# Note that upstream uses a different extension for included source files
# (.cxx, as opposed to .cpp for compiled ones).
#
lib{onemath}: include/hxx{*}                            \
              blas/hxx{*} blas/backends/hxx{*}          \
              lapack/hxx{*} lapack/backends/hxx{*}      \
              dft/hxx{*} dft/backends/hxx{*}            \
              rng/hxx{*} rng/backends/hxx{*}            \
              sparse_blas/hxx{*} sparse_blas/backends/hxx{*}

lib{onemath_blas_mklcpu}: include/hxx{*}                        \
                          blas/hxx{*} blas/backends/hxx{*}      \
                          blas/backends/mkl_common/hxx{**}      \
                          blas/backends/mklcpu/hxx{**}

lib{onemath_blas_mklcpu}: blas/backends/file{*.cxx}             \
                          blas/backends/mkl_common/file{**.cxx} \
                          blas/backends/mklcpu/file{**.cxx}: include = adhoc

lib{onemath_lapack_mklcpu}: include/hxx{*}                              \
                            lapack/hxx{*} lapack/backends/hxx{*}        \
                            lapack/backends/mkl_common/hxx{**}          \
                            lapack/backends/mklcpu*/hxx{**}

lib{onemath_lapack_mklcpu}: lapack/backends/file{*.cxx}                 \
                            lapack/backends/mkl_common/file{**.cxx}     \
                            lapack/backends/mklcpu/file{**.cxx}: include = adhoc

lib{onemath_dft_mklcpu}: include/hxx{*}                         \
                         dft/hxx{*} dft/backends/hxx{*}         \
                         dft/backends/mklcpu/hxx{**}

lib{onemath_dft_mklcpu}: dft/file{*.cxx} dft/backends/file{*.cxx}       \
                         dft/backends/mklcpu/file{**.cxx}: include = adhoc

lib{onemath_rng_mklcpu}: include/hxx{*}                         \
                         rng/hxx{*} rng/backends/hxx{*}         \
                         rng/backends/mklcpu/hxx{**}

lib{onemath_rng_mklcpu}: rng/backends/file{*.cxx}               \
                         rng/backends/mklcpu/file{**.cxx}: include = adhoc

lib{onemath_sparse_blas_mklcpu}: include/hxx{*}                                 \
                                 sparse_blas/hxx{*} sparse_blas/backends/hxx{*} \
                                 sparse_blas/backends/mkl_common/hxx{**}        \
                                 sparse_blas/backends/mklcpu/hxx{**}

lib{onemath_sparse_blas_mklcpu}:                \
  sparse_blas/backends/file{*.cxx}              \
  sparse_blas/backends/mkl_common/file{**.cxx}  \
  sparse_blas/backends/mklcpu/file{**.cxx}: include = adhoc

onemath_src = blas/cxx{blas_loader}             \
              dft/backends/cxx{descriptor}      \
              dft/cxx{dft_loader}               \
              lapack/cxx{lapack_loader}         \
              rng/cxx{rng_loader}               \
              sparse_blas/cxx{sparse_blas_loader}

blas_mklcpu_src   = blas/backends/mklcpu/cxx{*}
lapack_mklcpu_src = lapack/backends/mklcpu/cxx{*}
dft_mklcpu_src    = dft/backends/mklcpu/cxx{*}
rng_mklcpu_src    = rng/backends/mklcpu/cxx{*}
sparse_blas_mklcpu_src = sparse_blas/backends/mklcpu/cxx{*}

# Declare each library's host objects as prerequisites (see
# sycl_compilation.build for details).
#
# p: <library-name>@<sources-variable>
#
for p: onemath@onemath_src                      \
       onemath_blas_mklcpu@blas_mklcpu_src      \
       onemath_lapack_mklcpu@lapack_mklcpu_src  \
       onemath_dft_mklcpu@dft_mklcpu_src        \
       onemath_rng_mklcpu@rng_mklcpu_src        \
       onemath_sparse_blas_mklcpu@sparse_blas_mklcpu_src
{
  ln = $first($p)  # Library name
  sv = $second($p) # Source files variable name

  for t: $($sv)
  {
    n = $name($t)
    d = $directory($t)

    libs{$ln}: $d/objs{$(n)_host.so.o}
    liba{$ln}: $d/obja{$(n)_host.a.o}
  }
}

# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

cxx.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src"       \
                "-I$out_pfx_inc" "-I$src_pfx_inc"       \
                "-I$src_pfx_src/include/"

if ($cxx.target.class == 'windows')
  objs{*}: cxx.poptions += -Donemath_EXPORTS

for d: blas lapack dft rng sparse_blas
  $d/backends/{objs obja}{*}: cxx.poptions += $backend_poptions

if ($cxx.class == 'gcc')
{
  # From upstream/cmake/WarningsUtils.cmake.
  #
          dft/backends/{objs obja}{*}                                   \
  sparse_blas/backends/{objs obja}{*}: cxx.coptions += -Wall -Wextra    \
                                                       -Wshadow         \
                                                       -Wconversion     \
                                                       -Wpedantic
}

# Arrange for all (SYCL) sources to be compiled in two passes (see
# sycl_compilation.build).
#
sycl_lib_src = $onemath_src
for d: blas lapack dft rng sparse_blas
{
  for b: $backends
    sycl_lib_src += $($(d)_$(b)_src)
}
import [once] buildfile{sycl_compilation}

# Libraries
#
# Note: have to specify shared and static explicitly to get libraries added
# after objects (because we work with objs{} and obja{} instead of obj{}).
#
{libs liba}{onemath}:               $common_libs
{libs liba}{onemath_blas_mklcpu}:   $common_libs $mkl_sycl_blas $backend_libs
{libs liba}{onemath_lapack_mklcpu}: $common_libs $mkl_sycl_lapack $backend_libs
{libs liba}{onemath_dft_mklcpu}:    $common_libs $mkl_sycl_dft $backend_libs
# Note: as per upstream, rng_mklcpu's libraries differ from the rest (and even
# from rng_mklgpu!). It does not link to mkl_sycl_rng or mkl_opencl, and also
# is the only target that links to libstdc++. Not sure why; seems like a
# mistake. Might be due to it being the only one that links to the MKL::MKL
# (non-SYCL) cmake target whereas all of the test link to MKL::MKL_SYCL.
#
{libs liba}{onemath_rng_mklcpu}:    $common_libs $mkl_intel_ilp64       \
                                                 $mkl_tbb_thread        \
                                                 $mkl_core              \
                                                 $mkl_tbb

{libs liba}{onemath_sparse_blas_mklcpu}: $common_libs           \
                                         $mkl_sycl_sparse       \
                                         $backend_libs

lib{$all_libs}: cxx.loptions += $cxx_loptions

if ($cxx.target.class != 'windows')
{
  lib{$all_libs}:         cxx.libs += -ldl
  lib{$all_backend_libs}: cxx.libs += -lm
}

if ($cxx.target.system != 'win32-msvc')
  lib{$all_backend_libs}: cxx.libs += -pthread

# Export options.
#
incdirs = "-I$out_pfx_inc" "-I$src_pfx_inc"     \
          "-I$out_pfx_src"

lib{onemath}:
{
  cxx.export.poptions = $incdirs
  cxx.export.libs     = $common_export_libs
}

lib{$all_backend_libs}:
{
  cxx.export.poptions = $incdirs $backend_export_poptions
  cxx.export.libs     = $common_export_libs $backend_export_libs
}

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{$all_libs}: bin.lib.version = "-$version.project_id"
else
  lib{$all_libs}: bin.lib.version = "-$version.major.$version.minor"

# @@ TODO Confirm installation works. The headers do seem to get installed
#    properly (due to the well-structured upstream source directories) but I
#    have not run the tests against the installed libraries.
#
# Don't install private headers.
#
{hxx ixx txx}{*}: install = false
