#intf_libs = # Interface dependencies.
#impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

import! clang_offload_packager = icpx%exe{clang-offload-packager}

using autoconf

# Public headers.
#
pub = [dir_path] ../include/oneapi/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

supported_backends = mklcpu \
                     mklgpu

# Fail if no supported backends are enabled.
#
backends = [null]

if ($build.mode != 'skeleton')
{
  for b: $supported_backends
  {
    if $(config.liboneMath.enable_$(b)_backend)
      backends += $b
  }

  ifn $backends
    fail "no supported backends enabled"
  else
    text "enabled backends:" $backends
}

enable_blas = ($config.liboneMath.enable_mklcpu_backend ||      \
               $config.liboneMath.enable_mklgpu_backend)

all_libs = onemath              \
           onemath_blas_mklcpu  \
           onemath_blas_mklgpu

./: lib{onemath}:             include = true
./: lib{onemath_blas_mklcpu}: include = $config.liboneMath.enable_mklcpu_backend
./: lib{onemath_blas_mklgpu}: include = $config.liboneMath.enable_mklgpu_backend

# Public headers.
#
lib{onemath}: $pub/{$pub_hdrs} oneapi/math/detail/hxx{config}
lib{onemath_blas_mklcpu}: $pub/{$pub_hdrs} oneapi/math/detail/hxx{config}

# Metadata.
#
lib{onemath}:
{
  export.metadata = 1 libonemath

  libonemath.enable_armpl_backend = $config.liboneMath.enable_armpl_backend
  libonemath.enable_armpl_openrng = $config.liboneMath.enable_armpl_openrng
  libonemath.enable_cublas_backend = $config.liboneMath.enable_cublas_backend
  libonemath.enable_cufft_backend = $config.liboneMath.enable_cufft_backend
  libonemath.enable_curand_backend = $config.liboneMath.enable_curand_backend
  libonemath.enable_cusolver_backend = $config.liboneMath.enable_cusolver_backend
  libonemath.enable_cusparse_backend = $config.liboneMath.enable_cusparse_backend
  libonemath.enable_mklcpu_backend = $config.liboneMath.enable_mklcpu_backend
  libonemath.enable_mklgpu_backend = $config.liboneMath.enable_mklgpu_backend
  libonemath.enable_netlib_backend = $config.liboneMath.enable_netlib_backend
  libonemath.enable_generic_blas_backend = $config.liboneMath.enable_generic_blas_backend
  libonemath.enable_generic_blas_backend_amd_gpu = $config.liboneMath.enable_generic_blas_backend_amd_gpu
  libonemath.enable_generic_blas_backend_intel_cpu = $config.liboneMath.enable_generic_blas_backend_intel_cpu
  libonemath.enable_generic_blas_backend_intel_gpu = $config.liboneMath.enable_generic_blas_backend_intel_gpu
  libonemath.enable_generic_blas_backend_nvidia_gpu = $config.liboneMath.enable_generic_blas_backend_nvidia_gpu
  libonemath.generic_blas_enable_complex = $config.liboneMath.generic_blas_enable_complex
  libonemath.generic_blas_enable_usm = $config.liboneMath.generic_blas_enable_usm
  libonemath.enable_portfft_backend = $config.liboneMath.enable_portfft_backend
  libonemath.enable_rocblas_backend = $config.liboneMath.enable_rocblas_backend
  libonemath.enable_rocfft_backend = $config.liboneMath.enable_rocfft_backend
  libonemath.enable_rocrand_backend = $config.liboneMath.enable_rocrand_backend
  libonemath.enable_rocsolver_backend = $config.liboneMath.enable_rocsolver_backend
  libonemath.enable_rocsparse_backend = $config.liboneMath.enable_rocsparse_backend

  # True if the BLAS domain is enabled.
  #
  libonemath.enable_blas = $enable_blas
}

# Generate config.hpp.
#
oneapi/math/detail/hxx{config}: in{config}
{
  autoconf.flavor = cmake

  ONEMATH_ENABLE_ARMPL_BACKEND = $config.liboneMath.enable_armpl_backend
  ONEMATH_ENABLE_ARMPL_OPENRNG = $config.liboneMath.enable_armpl_openrng
  ONEMATH_ENABLE_CUBLAS_BACKEND = $config.liboneMath.enable_cublas_backend
  ONEMATH_ENABLE_CUFFT_BACKEND = $config.liboneMath.enable_cufft_backend
  ONEMATH_ENABLE_CURAND_BACKEND = $config.liboneMath.enable_curand_backend
  ONEMATH_ENABLE_CUSOLVER_BACKEND = $config.liboneMath.enable_cusolver_backend
  ONEMATH_ENABLE_CUSPARSE_BACKEND = $config.liboneMath.enable_cusparse_backend
  ONEMATH_ENABLE_MKLCPU_BACKEND = $config.liboneMath.enable_mklcpu_backend
  ONEMATH_ENABLE_MKLGPU_BACKEND = $config.liboneMath.enable_mklgpu_backend
  ONEMATH_ENABLE_NETLIB_BACKEND = $config.liboneMath.enable_netlib_backend
  ONEMATH_ENABLE_GENERIC_BLAS_BACKEND = $config.liboneMath.enable_generic_blas_backend
  ONEMATH_ENABLE_GENERIC_BLAS_BACKEND_AMD_GPU = $config.liboneMath.enable_generic_blas_backend_amd_gpu
  ONEMATH_ENABLE_GENERIC_BLAS_BACKEND_INTEL_CPU = $config.liboneMath.enable_generic_blas_backend_intel_cpu
  ONEMATH_ENABLE_GENERIC_BLAS_BACKEND_INTEL_GPU = $config.liboneMath.enable_generic_blas_backend_intel_gpu
  ONEMATH_ENABLE_GENERIC_BLAS_BACKEND_NVIDIA_GPU = $config.liboneMath.enable_generic_blas_backend_nvidia_gpu
  ONEMATH_GENERIC_BLAS_ENABLE_COMPLEX = $config.liboneMath.generic_blas_enable_complex
  ONEMATH_GENERIC_BLAS_ENABLE_USM = $config.liboneMath.generic_blas_enable_usm
  ONEMATH_ENABLE_PORTFFT_BACKEND = $config.liboneMath.enable_portfft_backend
  ONEMATH_ENABLE_ROCBLAS_BACKEND = $config.liboneMath.enable_rocblas_backend
  ONEMATH_ENABLE_ROCFFT_BACKEND = $config.liboneMath.enable_rocfft_backend
  ONEMATH_ENABLE_ROCRAND_BACKEND = $config.liboneMath.enable_rocrand_backend
  ONEMATH_ENABLE_ROCSOLVER_BACKEND = $config.liboneMath.enable_rocsolver_backend
  ONEMATH_ENABLE_ROCSPARSE_BACKEND = $config.liboneMath.enable_rocsparse_backend

  # @@ TODO This controls only dllimport/export so not sure why it's defined
  #    in a header.
  #
  ONEMATH_BUILD_SHARED_LIBS = true
}

# Private headers and sources as well as dependencies.
#

onemath_src = blas/cxx{blas_loader}             \
              dft/backends/cxx{descriptor}      \
              dft/cxx{dft_loader}               \
              lapack/cxx{lapack_loader}         \
              rng/cxx{rng_loader}               \
              sparse_blas/cxx{sparse_blas_loader}

blas_mklcpu_src = blas/backends/mklcpu/cxx{mklcpu_batch}        \
                  blas/backends/mklcpu/cxx{mklcpu_extensions}   \
                  blas/backends/mklcpu/cxx{mklcpu_level1}       \
                  blas/backends/mklcpu/cxx{mklcpu_level2}       \
                  blas/backends/mklcpu/cxx{mklcpu_level3}       \
                  blas/backends/mklcpu/cxx{mklcpu_wrappers}

# @@ TODO Private headers
#
for t: $onemath_src
{
  n = $name($t)
  d = $directory($t)

  libs{onemath}: $d/objs{$(n)_host.so.o}
  liba{onemath}: $d/obja{$(n)_host.a.o}
}

for t: $blas_mklcpu_src
{
  n = $name($t)
  d = $directory($t)

  libs{onemath_blas_mklcpu}: $d/objs{$(n)_host.so.o}
  liba{onemath_blas_mklcpu}: $d/obja{$(n)_host.a.o}
}

# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

cxx.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src"       \
                "-I$out_pfx_inc" "-I$src_pfx_inc"

# $src_pfx_src/include/: "function_table_initializer.hpp"
#
cxx.poptions += "-I$src_pfx_src/include/"

# @@ TODO Probably necessary all backends.
#
blas/backends/
{
  cxx.poptions += $backend_poptions
}

if ($cxx.target.class == 'windows')
  objs{*}: cxx.poptions += -Donemath_EXPORTS

dft/backends/
{
  if ($cxx.class == 'gcc')
  {
    # From upstream/cmake/WarningsUtils.cmake.
    #
    {objs obja}{*}: cxx.coptions += -Wall -Wextra -Wshadow -Wconversion -Wpedantic
  }
}

sycl_lib_src = $onemath_src $blas_mklcpu_src
import [once] buildfile{sycl_compilation}

# Libraries

lib{onemath}: $common_libs
{
  cxx.libs += $common_sys_libs
}

lib{onemath_blas_mklcpu}: $common_libs $backend_libs
{
  cxx.libs += $common_sys_libs $backend_sys_libs
}

# Export options.
#
incdirs = "-I$out_pfx_inc" "-I$src_pfx_inc"     \
          "-I$out_pfx_src"

lib{onemath}:
{
  cxx.export.poptions = $incdirs $libonemath_export_poptions
  cxx.export.libs     = $libonemath_export_libs
}

lib{onemath_blas_mklcpu}:
{
  cxx.export.poptions = $incdirs
  cxx.export.libs     =
}

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{$all_libs}: bin.lib.version = "-$version.project_id"
else
  lib{$all_libs}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
#
{hxx ixx txx}{*}: install = false
