intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

import! clang_offload_packager = icpx%exe{clang-offload-packager}

using autoconf

# Public headers.
#
pub = [dir_path] ../include/oneapi/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

supported_backends = mklcpu \
                     mklgpu

# Fail if no supported backends are enabled.
#
backends = [null]

if ($build.mode != 'skeleton')
{
  for b: $supported_backends
  {
    if $(config.liboneMath.enable_$(b)_backend)
      backends += $b
  }

  ifn $backends
    fail "no supported backends enabled"
  else
    info "enabled backends:" $backends
}

# Public headers.
#
./: lib{onemath}: $pub/{$pub_hdrs} oneapi/math/detail/hxx{config}

# Generate config.hpp.
#
oneapi/math/detail/hxx{config}: in{config}
{
  autoconf.flavor = cmake

  ONEMATH_ENABLE_ARMPL_BACKEND = $config.liboneMath.enable_armpl_backend
  ONEMATH_ENABLE_ARMPL_OPENRNG = false
  ONEMATH_ENABLE_CUBLAS_BACKEND = $config.liboneMath.enable_cublas_backend
  ONEMATH_ENABLE_CUFFT_BACKEND = $config.liboneMath.enable_cufft_backend
  ONEMATH_ENABLE_CURAND_BACKEND = $config.liboneMath.enable_curand_backend
  ONEMATH_ENABLE_CUSOLVER_BACKEND = $config.liboneMath.enable_cusolver_backend
  ONEMATH_ENABLE_CUSPARSE_BACKEND = $config.liboneMath.enable_cusparse_backend
  ONEMATH_ENABLE_MKLCPU_BACKEND = $config.liboneMath.enable_mklcpu_backend
  ONEMATH_ENABLE_MKLGPU_BACKEND = $config.liboneMath.enable_mklgpu_backend
  ONEMATH_ENABLE_NETLIB_BACKEND = $config.liboneMath.enable_netlib_backend
  ONEMATH_ENABLE_GENERIC_BLAS_BACKEND = $config.liboneMath.enable_generic_blas_backend
  ONEMATH_ENABLE_GENERIC_BLAS_BACKEND_AMD_GPU = false
  ONEMATH_ENABLE_GENERIC_BLAS_BACKEND_INTEL_CPU = false
  ONEMATH_ENABLE_GENERIC_BLAS_BACKEND_INTEL_GPU = false
  ONEMATH_ENABLE_GENERIC_BLAS_BACKEND_NVIDIA_GPU = false
  ONEMATH_GENERIC_BLAS_ENABLE_COMPLEX = false
  ONEMATH_GENERIC_BLAS_ENABLE_USM = false
  ONEMATH_ENABLE_PORTFFT_BACKEND = $config.liboneMath.enable_portfft_backend
  ONEMATH_ENABLE_ROCBLAS_BACKEND = $config.liboneMath.enable_rocblas_backend
  ONEMATH_ENABLE_ROCFFT_BACKEND = $config.liboneMath.enable_rocfft_backend
  ONEMATH_ENABLE_ROCRAND_BACKEND = $config.liboneMath.enable_rocrand_backend
  ONEMATH_ENABLE_ROCSOLVER_BACKEND = $config.liboneMath.enable_rocsolver_backend
  ONEMATH_ENABLE_ROCSPARSE_BACKEND = $config.liboneMath.enable_rocsparse_backend

  # @@ TODO This controls only dllimport/export so not sure why it's defined
  #    in a header.
  #
  ONEMATH_BUILD_SHARED_LIBS = true
}

# Private headers and sources as well as dependencies.
#
# The desired compilation commands for a source file foo.cpp is as follows:
#
#   Extract dependencies and compile the device object from foo.cpp. Then
#   convert it into an offload binary (an object that can be embedded inside
#   the host object).
#
#     icpx -fsycl --offload-new-driver -fsycl-device-only
#          -MD -E -o foo_device.ii foo.cpp
#     icpx -fsycl --offload-new-driver -fsycl-device-only
#          -c foo_device.ii -o foo_device.o
#     clang-offload-packager -o foo_device_offload.o
#                            --image=file=foo_device.o,triple=spir64-unknown-unknown
#
#   Extract dependencies and compile the host object, also from foo.cpp. Then
#   embed the device offload binary inside the host object's offload section.
#
#     icpx -fsycl --offload-new-driver -fsycl-host-only
#          -MD -E -o foo_host.ii foo.cpp
#     icpx -fsycl --offload-new-driver -fsycl-host-only
#          -Xclang -fembed-offload-object=foo_device_offload.so.o
#          -o foo_host.o -c foo_host.ii
#
#   Link the library using the various host objects with the device code
#   embedded in them as input.
#
#     icpx -shared -o libonemath.so foo_host.o bar_host.o baz_host.o
#
# This sequence can be verified by compiling the device and host objects in a
# single compiler invocation (the default method of operation) with debug
# output enabled (-###):
#
#   icpx -### -fsycl --offload-new-driver -o foo.o foo.cpp
#
libs{onemath}: blas/objs{blas_loader_host.so.o}
liba{onemath}: blas/obja{blas_loader_host.a.o}

              # lapack/cxx{lapack_loader}
              # rng/cxx{rng_loader}               \
              # dft/backends/cxx{descriptor}      \
              # dft/cxx{dft_loader}               \
              # sparse_blas/cxx{sparse_blas_loader}

# Host object
#
blas/objs{blas_loader_host.so.o}: blas/cxx{blas_loader}
blas/objs{blas_loader_host.so.o}: blas/objs{blas_loader_device_offload.so.o}: \
  include = adhoc

blas/obja{blas_loader_host.a.o}:  blas/cxx{blas_loader}
blas/obja{blas_loader_host.a.o}:  blas/obja{blas_loader_device_offload.a.o}: \
  include = adhoc

# Device object
#
blas/objs{blas_loader_device.so.o}: blas/cxx{blas_loader}
blas/obja{blas_loader_device.a.o}:  blas/cxx{blas_loader}

# Device offload object
#
blas/objs{blas_loader_device_offload.so.o}: blas/objs{blas_loader_device.so.o}
blas/obja{blas_loader_device_offload.a.o}:  blas/obja{blas_loader_device.a.o}

# Generate the device offload object using the clang-offload-packager tool.
#
# spir64-unknown-unknown: From the `icpx -### -fsycl -fsycl-device-only
#                         foo.cpp` output.
#
objs{~'/(.*)_offload.so/'}: objs{~'/\1.so/'}
{{
  diag clang-offload-packager $path($<[0]) -> $path($>[0])

  $clang_offload_packager \
  -o $path($>[0]) --image=file="$path($<[0])",triple=spir64-unknown-unknown
}}

obja{~'/(.*)_offload.a/'}: obja{~'/\1.a/'}
{{
  diag clang-offload-packager $path($<[0]) -> $path($>[0])

  $clang_offload_packager \
  -o $path($>[0]) --image=file="$path($<[0])",triple=spir64-unknown-unknown
}}

# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

cxx.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src"       \
                "-I$out_pfx_inc" "-I$src_pfx_inc"       \
                "-I$src_pfx_src/include/"

# Need to add this path manually because we don't pass -fsycl during header
# extraction. @@ TODO Make this path configurable.
#
cxx.poptions += "-isystem/opt/intel/oneapi/compiler/2025.2/include/"

#obja{*}: cxx.poptions += -DONEAPI_STATIC_BUILD
#objs{*}: cxx.poptions += -DONEAPI_SHARED_BUILD

objs{*}: cxx.coptions += -fsycl --offload-new-driver
obja{*}: cxx.coptions += -fsycl --offload-new-driver

# Build options for the host object:
#
# - Compile for host only
# - Embed the device offload object inside the host object
#
blas/objs{blas_loader_host.so.o}: cxx.coptions +=       \
  -fsycl-host-only                                      \
  -Xclang -fembed-offload-object="$out_base/blas/blas_loader_device_offload.so.o"

blas/obja{blas_loader_host.a.o}: cxx.coptions +=        \
  -fsycl-host-only                                      \
  -Xclang -fembed-offload-object="$out_base/blas/blas_loader_device_offload.a.o"

# Build options for the device object:
#
# - Compile for the device only
#
blas/objs{blas_loader_device.so.o}: cxx.coptions += -fsycl-device-only
blas/obja{blas_loader_device.a.o}:  cxx.coptions += -fsycl-device-only

# Export options.
#
lib{onemath}:
{
  cxx.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc"
  cxx.export.libs = $intf_libs
}

#liba{onemath}: cxx.export.poptions += -DONEAPI_STATIC
#libs{onemath}: cxx.export.poptions += -DONEAPI_SHARED

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{onemath}: bin.lib.version = "-$version.project_id"
else
  lib{onemath}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
#
{hxx ixx txx}{*}: install = false
